#!/bin/sh
ocamlfind ocamldep -syntax camlp4o -package batteries.pa_openin.syntax,batteries.pa_where.syntax,batteries.pa_batteries.syntax,batteries.pa_type_conv.syntax,batteries.pa_comprehension.syntax,batteries.pa_strings.syntax,batteries.sexplib.syntax -package batteries $@
